name: Deploy to GH

on: [push]

jobs:
  test:
    name: Test and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '9'

    - name: Test something (currently we have no tests)
      run: |
        npm install -g gulp-cli@2.3.0
        export NODE_OPTIONS=--use-openssl-ca
        npm install
        gulp build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
      if: github.ref == 'refs/heads/master' && job.status == 'success'
